### PR TITLE
Remove unnecessary `router.refresh()` usage

### PR DESCRIPTION
**Pull request by karlhorky**
Since Next.js 13.4.6, calling `cookies().set()` in a Server Action invalidates the client cache:

- https://github.com/vercel/next.js/issues/42991#issuecomment-1615836329
- PR https://github.com/vercel/next.js/pull/51290

This means that we no longer need to call router.refresh() anymore, which means we can:

- remove the `router.refresh()` in the logout button Client Component and remove the logout Client Component
- remove the `router.refresh()` in the `FruitCommentForm` Client Component

### CODE REVIEW

**Review by Josehower — APPROVED** [review]
LGTM! 

scheduled to merge on 18th

**Comment by karlhorky** [comment]
@ProchaLu found an issue with this: `cookies().set(...)` no longer clears the client cache starting in `next@13.4.11-canary.1` - he's going to open an issue and post the link to it

**Comment by ProchaLu** [comment]
we found an issue with this: `cookies().set(...)` no longer clears the client cache starting in `next@13.4.11-canary.1` :

- https://github.com/vercel/next.js/issues/53261

**Comment by karlhorky** [comment]
@ProchaLu seems like this was fixed with tests:

- PR fixing the problem https://github.com/vercel/next.js/pull/53373
- PR adding tests https://github.com/vercel/next.js/pull/53494

Can you upgrade and test again?

**Comment by ProchaLu** [comment]
Upgraded my [test project](https://github.com/ProchaLu/next-loading-state) and tested `cookie(set)` and `cookie(get)` again. Everything works as expected now without refreshing the page. 

https://github.com/upleveled/next-js-example-spring-2023-vienna-austria/assets/80746311/c06e1009-2d8b-4c85-b624-de84f2cfc96b

**Pull request merged**
